export const ADD_QUOTE = "ADD_QUOTE";

export const GET_CHARACTER_DETAIL = "GET_CHARACTER_DETAIL";

export const EMPTY_CHARACTER_DETAIL = "EMPTY_CHARACTER_DETAIL";

export const GET_CHARACTERS = "GET_CHARACTERS";

export const GET_EPISODES = "GET_EPISODES";

export const EMPTY_EPISODE_DETAIL = "EMPTY_EPISODE_DETAIL";

export const GET_EPISODE_DETAIL = "GET_EPISODE_DETAIL";
